src/MZJ/YabBundle/Entity/Post.php
<?php

/*
 * This file is part of the Yabb package.
 *
 * (c) Marko Jovanovic <markozjovanovic@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace MZJ\YabBundle\Entity;

use DoctrineExtensions\Taggable\Taggable;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * MZJ\YabBundle\Entity\Post
 *
 * Post entity
 *
 * @author Marko Jovanovic <markozjovanovic@gmail.com>
 */
class Post implements Taggable
{
    /**
     * @var integer $id
     */
    private $id;

    /**
     * @var string $title
     */
    private $title;

    /**
     * @var string $content
     */
    private $content;

    /**
     * @var \DateTime $created_at
     */
    private $created_at;

    /**
     * @var \DateTime $updated_at
     */
    private $updated_at;

    /**
     * @var string $slug
     */    
    private $slug;
    
    /**
     * @var ArrayCollection $comments
     */    
    private $comments;
    
    /**
     * @var ArrayCollection $categories
     */    
    private $categories;    
    
    
    /**
     * @var boolean $enabled
     */    
    private $enabled = true;     
    
    /**
     * @var boolean $commentsEnabled
     */    
    private $commentsEnabled = false; 
    
    /**
     * 
     */
    private $tags;
    
    /**
     *
     * @var string 
     */
    private $abstract;
    
    /**
     * 
     */
    public function __construct() 
    {
        $this->created_at = new \DateTime('now');
    }
    
    /**
     * 
     * @return type
     */
    public function getTags()
    {
        $this->tags = $this->tags ?: new ArrayCollection();

        return $this->tags;
    }
    
    public function setTags($tags) 
    {
        $this->tags = $tags;
    }

    /**
     * 
     * @return string
     */
    public function getTaggableType()
    {
        return 'post_tag';
    }

    /**
     * 
     * @return type
     */
    public function getTaggableId()
    {
        return $this->getId();
    }
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Post
     */
    public function setTitle($title)
    {
        $this->title = $title;
    
        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set content
     *
     * @param string $content
     * @return Post
     */
    public function setContent($content)
    {
        $this->content = $content;
    
        return $this;
    }

    /**
     * Get content
     *
     * @return string 
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set created_at
     *
     * @param \DateTime $createdAt
     * @return Post
     */
    public function setCreatedAt($createdAt)
    {
        $this->created_at = $createdAt;
    
        return $this;
    }
    
    /**
     * Get created_at
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Set updated_at
     *
     * @param \DateTime $updatedAt
     * @return Post
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updated_at = $updatedAt;
    
        return $this;
    }

    /**
     * Get updated_at
     *
     * @return \DateTime 
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }



    /**
     * Set slug
     *
     * @param string $slug
     * @return Post
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;
    
        return $this;
    }

    /**
     * Get slug
     *
     * @return string 
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Add comments
     *
     * @param MZJ\YabBundle\Entity\Comment $comments
     * @return Post
     */
    public function addComment(\MZJ\YabBundle\Entity\Comment $comments)
    {
        //$comment->setPost($this);
        
        $this->comments[] = $comments;
        
        return $this;
    }

    /**
     * Remove comments
     *
     * @param MZJ\YabBundle\Entity\Comment $comments
     */
    public function removeComment(\MZJ\YabBundle\Entity\Comment $comments)
    {
        $this->comments->removeElement($comments);
    }

    /**
     * Get comments
     *
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getComments()
    {
        return $this->comments;
    }

    /**
     * Add categories
     *
     * @param MZJ\YabBundle\Entity\Category $categories
     * @return Post
     */
    public function addCategorie(\MZJ\YabBundle\Entity\Category $categories)
    {
        $this->categories[] = $categories;
    
        return $this;
    }

    /**
     * Remove categories
     *
     * @param MZJ\YabBundle\Entity\Category $categories
     */
    public function removeCategorie(\MZJ\YabBundle\Entity\Category $categories)
    {
        $this->categories->removeElement($categories);
    }

    /**
     * Get categories
     *
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getCategories()
    {
        return $this->categories;
    }
    
    /**
     * Add categories
     *
     * @param MZJ\YabBundle\Entity\Category $categories
     * @return Post
     */
    public function setCategories($categories)
    {
        $this->categories = $categories;
    
        return $this;
    }
    
 
    /**
     * Get enabled
     *
     * @return boolean
     */
    public function getEnabled()
    {
        return $this->enabled;
    }
    
    /**
     * Set enabled
     *
     * @return boolean
     */
    public function setEnabled($enabled)
    {
        $this->enabled = $enabled;
    }
    
    /**
     * Get commentsEnabled
     *
     * @return boolean
     */
    public function getCommentsEnabled()
    {
        return $this->commentsEnabled;
    }
    
    /**
     * Set commentsEnabled
     *
     * @return boolean
     */
    public function setCommentsEnabled($commentsEnabled)
    {
        $this->commentsEnabled = $commentsEnabled;
    }
    
    /**
     * 
     * @return type
     */
    public function getAbstract()
    {
        return $this->abstract;
    }
    
    /**
     * 
     * @param type $abstract
     */
    public function setAbstract($abstract)
    {
        $this->abstract = $abstract;
    }
}

src/MZJ/YabBundle/Form/PostType.php
<?php

namespace MZJ\YabBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('content')
            ->add('abstract')
            ->add('created_at')
            ->add('enabled', null, array('required' => false))
            ->add('commentsEnabled', null, array('required' => false))
            ->add('categories')
            ->add('tags', 'hidden', array('property_path' => false))
         ;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'MZJ\YabBundle\Entity\Post'
        ));
    }

    public function getName()
    {
        return 'mzj_yabbundle_posttype';
    }
}

src/MZJ/YabBundle/Controller/PostController.php
<?php

/*
 * This file is part of the Yabb package.
 *
 * (c) Marko Jovanovic <markozjovanovic@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace MZJ\YabBundle\Controller;

use Symfony\Component\HttpFoundation\Request,
    Symfony\Bundle\FrameworkBundle\Controller\Controller,
    MZJ\YabBundle\Entity\Post,
    MZJ\YabBundle\Form\PostType;

/**
 * MZJ\YabBundle\Controller\PostController
 *
 * Post controller
 *
 * @author Marko Jovanovic <markozjovanovic@gmail.com>
 */
class PostController extends Controller
{
    /**
     * Lists all Post entities.
     *
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('MZJYabBundle:Post')->findAll();

        return $this->render('MZJYabBundle:Post:index.html.twig', array(
            'entities' => $entities,
        ));
    }

    /**
     * Finds and displays a Post entity.
     *
     */
    public function viewAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        $tagManager = $this->get('fpn_tag.tag_manager');
        
        $entity = $em->getRepository('MZJYabBundle:Post')->getPost($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Post entity.');
        }

        $tagManager->loadTagging($entity);
        
        return $this->render('MZJYabBundle:Post:view.html.twig', array(
            'post'      => $entity
         ));
    }

    /**
     * Displays a form to create a new Post entity.
     *
     */
    public function newAction()
    {
        $entity = new Post();
        $form   = $this->createForm(new PostType(), $entity);
        
        return $this->render('MZJYabBundle:Post:new.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView(),
        ));
    }

    /**
     * Creates a new Post entity.
     *
     */
    public function createAction(Request $request)
    {
        $data = $request->request->get('mzj_yabbundle_posttype');
        $tagsStr = $data['tags'];
        
        $entity  = new Post();
        
        $tagManager = $this->get('fpn_tag.tag_manager');
        
        $tags = $tagManager->loadOrCreateTags($tagManager->splitTagNames($tagsStr));

        // assign the foo tag to the post
        $tagManager->addTags($tags, $entity);
        
        $form = $this->createForm(new PostType(), $entity);
        $form->bind($request);
        
        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();
            
            // after flushing the post, tell the tag manager to actually save the tags
            $tagManager->saveTagging($entity);
            
            return $this->redirect($this->generateUrl('post_show', 
                    array(
                        'created' => $entity->getCreatedAt()->format('m-d-Y'),
                        'id' => $entity->getId(), 
                        'slug' => $entity->getSlug()
                    )
                    ));
        }

        return $this->render('MZJYabBundle:Post:new.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing Post entity.
     *
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('MZJYabBundle:Post')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Post entity.');
        }
        
        $tagManager = $this->get('fpn_tag.tag_manager');
        $tagManager->loadTagging($entity);

        $editForm = $this->createForm(new PostType(), $entity);
        $deleteForm = $this->createDeleteForm($id);

        return $this->render('MZJYabBundle:Post:edit.html.twig', array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Edits an existing Post entity.
     *
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $data = $request->request->get('mzj_yabbundle_posttype');
        $tagsStr = $data['tags'];
        
        $entity = $em->getRepository('MZJYabBundle:Post')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Post entity.');
        }
        
        $tagManager = $this->get('fpn_tag.tag_manager');
        
        $tags = $tagManager->loadOrCreateTags($tagManager->splitTagNames($tagsStr));
        
        $tagManager->replaceTags($tags, $entity);
        
        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createForm(new PostType(), $entity);
        $editForm->bind($request);

        
        if ($editForm->isValid()) {
            $em->persist($entity);
            $em->flush();

            // after flushing the post, tell the tag manager to actually save the tags
            $tagManager->saveTagging($entity);
            
            return $this->redirect($this->generateUrl('post_edit', array('id' => $id)));
        }

        return $this->render('MZJYabBundle:Post:edit.html.twig', array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Deletes a Post entity.
     *
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->bind($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('MZJYabBundle:Post')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Post entity.');
            }

            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('post'));
    }

    /**
     * Lists all Post entities.
     *
     */
    public function inCategoryAction($id, $slug)
    {
        $em = $this->getDoctrine()
                   ->getEntityManager();
         
        $repo = $em->getRepository('MZJYabBundle:Category');
        $category = $repo->find($id);
        $posts = $em->getRepository('MZJYabBundle:Post')->getPostsInCategory($category);

        return $this->render('MZJYabBundle:Post:inCategory.html.twig', array(
            'entities' => $posts,
        ));
    }
    
    /**
     * Lists all Post entities.
     *
     */
    public function withTagAction($tag)
    {
        $em = $this->getDoctrine()
                   ->getEntityManager();
         
        $ids = $em->getRepository('MZJYabBundle:Tag')->getResourceIdsForTag('post_tag', $tag);
        $posts = null;
        
        if(!empty($ids)) {
            $posts = $em->getRepository('MZJYabBundle:Post')->getPostsWithIds($ids);
        }

        return $this->render('MZJYabBundle:Post:withTag.html.twig', array(
            'entities' => $posts,
        ));
    }
    
    /**
     * 
     * @param type $id
     * @return type
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder(array('id' => $id))
            ->add('id', 'hidden')
            ->getForm()
        ;
    }
}

src/MZJ/YabBundle/Resources/views/Post/edit.html.twig
<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css">
<link rel="stylesheet" href="{{ asset('bundles/mzjyab/js/vendor/tag-it/css/jquery.tagit.css') }}" type="text/css" media="screen" />


{% block javascripts %}
    {{ parent() }}
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/jquery-ui.min.js" type="text/javascript" charset="utf-8"></script>
     {% javascripts 'bundles/mzjyab/js/vendor/tag-it/js/tag-it.js' %}
        <script src="{{ asset_url }}"></script>
    {% endjavascripts %}
{% endblock javascripts %}

<script type="text/javascript">
    $(document).ready(function() {
        $("#mzj_yabbundle_posttype_tags").tagit();
    });
</script>

<h1>Post edit</h1>

<form action="{{ path('post_update', { 'id': entity.id }) }}" method="post" {{ form_enctype(edit_form) }}>
  
    {% set value = '' %}
    
    {% for tag in entity.tags %}
        {% set value = value ~ tag ~ ',' %}
    {% endfor %}
    
    
    {{ form_widget(edit_form.tags, { 'attr': {'value': value} }) }}
    {{ form_widget(edit_form) }}
    <p>
        <button type="submit">Edit</button>
    </p>
</form>

<ul class="record_actions">
    <li>
        <a href="{{ path('post') }}">
            Back to the list
        </a>
    </li>
    <li>
        <form action="{{ path('post_delete', { 'id': entity.id }) }}" method="post">
            {{ form_widget(delete_form) }}
            <button type="submit">Delete</button>
        </form>
    </li>
</ul>

src/MZJ/YabBundle/Resources/views/Post/inCategory.html.twig
{% extends 'MZJYabBundle::layout.html.twig' %}

{% block main %}
    
    {{ parent() }}

    <section id="posts-list">
        {% for entity in entities %}
            {% include 'MZJYabBundle:Post:short.html.twig' with {'post': entity} %}
        {% else %}
            <h2>There are no posts :(</h2>
        {% endfor %}
    </section>


{% endblock main %}

src/MZJ/YabBundle/Resources/views/Post/index.html.twig
<h1>Post list</h1>

<table class="records_list">
    <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Content</th>
            <th>Created_at</th>
            <th>Updated_at</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
    {% for entity in entities %}
        <tr>
            <td><a href="{{ path('post_show', { 'created': entity.createdAt|date("m-d-Y"), 'id': entity.id, 'slug': entity.slug }) }}">{{ entity.id }}</a></td>
            <td>{{ entity.title }}</td>
            <td>{{ entity.content }}</td>
            <td>{% if entity.createdat %}{{ entity.createdat|date('Y-m-d H:i:s') }}{% endif %}</td>
            <td>{% if entity.updatedat %}{{ entity.updatedat|date('Y-m-d H:i:s') }}{% endif %}</td>
            <td>
                <ul>
                    <li>
                        <a href="{{ path('post_show', { 'created': entity.createdAt|date("m-d-Y"), 'id': entity.id, 'slug': entity.slug }) }}">show</a>
                    </li>
                    <li>
                        <a href="{{ path('post_edit', { 'id': entity.id }) }}">edit</a>
                    </li>
                </ul>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<ul>
    <li>
        <a href="{{ path('post_new') }}">
            Create a new entry
        </a>
    </li>
</ul>

src/MZJ/YabBundle/Resources/views/Post/new.html.twig
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js" type="text/javascript" charset="utf-8"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/jquery-ui.min.js" type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css">

<link rel="stylesheet" href="{{ asset('bundles/mzjyab/js/vendor/tag-it/css/jquery.tagit.css') }}" type="text/css" media="screen" />
<script type="text/javascript" src="{{ asset('bundles/mzjyab/js/vendor/tag-it/js/tag-it.js') }}" ></script>


<script type="text/javascript">
    $(document).ready(function() {
        $("#mytags").tagit({
            singleField: true,
            singleFieldNode: $('#mzj_yabbundle_posttype_tags')
        });
    });
</script>

<h1>Post creation</h1>

<form action="{{ path('post_create') }}" method="post" {{ form_enctype(form) }}>
    {{ form_widget(form) }}
    <p>
        <button type="submit">Create</button>
    </p>
</form>

<ul class="record_actions">
    <li>
        <a href="{{ path('post') }}">
            Back to the list
        </a>
    </li>
</ul>

<ul id="mytags">
    <!-- Existing list items will be pre-added to the tags -->
    <li>Tag1</li>
    <li>Tag2</li>
</ul>

src/MZJ/YabBundle/Resources/views/Post/short.html.twig
<article class="short-post">
    
    <h2>
        <a href="{{ path('MZJYabBundle_post_view', { 'id': post.id, 'slug': post.slug }) }}">
            {{ post.title }}
        </a>   
    </h2>
    
    <time  datetime="{{ post.createdAt|date('Y-m-d') }}" pubdate>
        <span class="day">{{ post.createdAt|date('d') }}</span>
        <span class="month">{{ post.createdAt|date('M') }}</span>
        <span class="year">{{ post.createdAt|date('Y') }}</span>
    </time>     
        
    <p class="abstract">{{ post.abstract }}</p>
    
    <p>
        <span class="categories"> { 
            {% for category in post.categories %}
                {{ category.name }}{% if loop.last == false %},{% endif %}
            {% endfor %} }
        </span>
        <span class="read-more">
            <a href="{{ path('MZJYabBundle_post_view', { 'created': post.createdAt|date("m-d-Y"), 'id': post.id, 'slug': post.slug }) }}">
                Read &#8594;
            </a>
        </span>
    </p>
    
</article>

src/MZJ/YabBundle/Resources/views/Post/show.html.twig
{% extends '::base.html.twig' %}

{% block body %}
<h1>Post</h1>

<table class="record_properties">
    <tbody>
        <tr>
            <th>Id</th>
            <td>{{ entity.id }}</td>
        </tr>
        <tr>
            <th>Title</th>
            <td>{{ entity.title }}</td>
        </tr>
        <tr>
            <th>Content</th>
            <td>{{ entity.content }}</td>
        </tr>
        <tr>
            <th>Categories</th>
            <td>{% for category in entity.categories %}{{ category }}, {% endfor %}</td>
        </tr>
        <tr>
            <th>Tags</th>
            <td>{% for tag in entity.tags %} {{ tag }}, {% endfor %}</td>
        </tr>
        <tr>
            <th>Created_at</th>
            <td>{{ entity.createdat|date('Y-m-d H:i:s') }}</td>
        </tr>
        <tr>
            <th>Updated_at</th>
            <td>{{ entity.updatedat|date('Y-m-d H:i:s') }}</td>
        </tr>
    </tbody>
</table>

<ul class="record_actions">
    <li>
        <a href="{{ path('post') }}">
            Back to the list
        </a>
    </li>
    <li>
        <a href="{{ path('post_edit', { 'id': entity.id }) }}">
            Edit
        </a>
    </li>
    <li>
        <form action="{{ path('post_delete', { 'id': entity.id }) }}" method="post">
            {{ form_widget(delete_form) }}
            <button type="submit">Delete</button>
        </form>
    </li>
</ul>


<ul>
    {% for comment in entity.comments %}
        <li>{{ comment.createdAt|date('m-d-Y') }} by: {{ comment.name }} <br> {{ comment.content }} </li>
    {% endfor %}
</ul>

{% endblock %}

src/MZJ/YabBundle/Resources/views/Post/view.html.twig
{% extends 'MZJYabBundle::layout.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css">
    <link rel="stylesheet" href="{{ asset('bundles/mzjyab/js/vendor/tag-it/css/jquery.tagit.css') }}" type="text/css" media="screen" />
{% endblock stylesheets %}

{% block javascripts %}
    {{ parent() }}
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/jquery-ui.min.js" type="text/javascript" charset="utf-8"></script>
     {% javascripts 'bundles/mzjyab/js/vendor/tag-it/js/tag-it.js' %}
        <script src="{{ asset_url }}"></script>
    {% endjavascripts %}
        
        <script type="text/javascript">
            $(document).ready(function() {
                $("#mzj_yabbundle_posttype_tags").tagit();
            });
        </script>
{% endblock javascripts %}




{% block title %}
    {{ post.title }} - Yab
{% endblock %}

{% block main %}
    
    {{ parent() }}

    <section id="post">
        <article>
            <h1>{{ post.title }}</h1>
            <p class="abstract">{{ post.abstract }}</p>
            <p>{{ post.content|raw }}</p>
            
            <p class="tags">
                Tags:
                {% for tag in post.tags %}
                    {{ tag.name }} {% if loop.last == false %},{% endif %}
                {% endfor %}
             </p>
             
        </article>
    </section>
    <section id="comments">
        {% if post.commentsEnabled %}
            {% render "MZJYabBundle:Comment:comments" with {'postId': post.id} %}
        {% else %}
            Comments disabled
        {% endif %}
    </section>

{% endblock main %}

src/MZJ/YabBundle/Resources/views/Post/withTag.html.twig
{% extends 'MZJYabBundle::layout.html.twig' %}

{% block main %}
    
    {{ parent() }}

    <section id="posts-list">
        {% for entity in entities %}
            {% include 'MZJYabBundle:Post:short.html.twig' with {'post': entity} %}
        {% else %}
            <h2>There are no posts :(</h2>
        {% endfor %}
    </section>


{% endblock main %}